version: '3.6'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=application
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    volumes:
      - ./script/docker-mysql/conf/:/etc/mysql/conf.d
      - ./script/docker-mysql/sql/:/docker-entrypoint-initdb.d
    command: --sql_mode=''

  redis:
    image: redis:5
    container_name: redis
    restart: always
    command: redis-server --requirepass credential
    ports:
      - 6379:6379

# https://github.com/sherifabdlnaby/elastdocker
#  es01:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
#    container_name: es01
#    environment:
#      - node.name=es01
#      - discovery.seed_hosts=es02
#      - cluster.initial_master_nodes=es01,es02
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata01:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#
#  es02:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
#    container_name: es02
#    environment:
#      - node.name=es02
#      - discovery.seed_hosts=es01
#      - cluster.initial_master_nodes=es01,es02
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata02:/usr/share/elasticsearch/data
#
#volumes:
#  esdata01:
#    driver: local
#  esdata02:
#    driver: local