logging:
  level:
    ROOT: INFO
    web: INFO

    # application
    jupyter.catalog: INFO

spring:
  application:
    name: Catalog

  main:
    allow-bean-definition-overriding: true

  profiles:
    active: local
    include:

#
# server
#
server:
  use-forward-headers: true
  port: ${APPLICATION_PORT:9091}
  servlet:
    session:
      cookie:
        http-only: true

#
# other micro services
#
services:
  notebook-endpoint: ${SERVICE_NOTEBOOK_ENDPOINT:localhost}
  notebook-port: ${SERVICE_NOTEBOOK_PORT:9092}

