swagger: "2.0"
info:
  title: Gateway
  version: 0.0.1
schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:

  # AUTH APIs
  /auth/whoiam:
    $ref: "./catalog-auth-api.yaml#/api/whoami"