swagger: "2.0"
info:
  title: Catalog
  version: 0.0.1
schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:

  # Auth API
  /auth/whoiam:
    $ref: "./catalog-auth-api.yaml#/api/whoami"

  # Notebook API
  /notebook/display:
    $ref: "./catalog-notebook-api.yaml#/api/display"
