swagger: "2.0"
info:
  title: Notebook
  version: 0.0.1
schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:

  # Notebook API
  /notebook/display:
    $ref: "./notebook-display-api.yaml#/api/display"